version: '3.8'
services:
  mysqldb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password


  app:
    depends_on:
      - mysqldb
    build: ./docker-proj
    restart: on-failure
    ports:
      - "3000:3000"